disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ben Jaynes"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

  [params.author]
  name = "Ben Jaynes"
  headline = "Building robots, rockets, circuit boards and more"
  bio = "Student"
  image = "img/atom.jpg"
